# Generated by Django 3.0.6 on 2020-08-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('midname', models.CharField(blank=True, max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('roll', models.IntegerField(unique=True)),
                ('img', models.ImageField(upload_to='uploads')),
                ('father_name', models.CharField(max_length=25)),
                ('mother_name', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='F', max_length=3)),
                ('dob', models.DateField()),
                ('sem', models.IntegerField()),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science'), ('CE', 'Civil'), ('EC', 'Electronics'), ('EE', 'Electrical')], default='CSE', max_length=3)),
                ('course', models.CharField(choices=[('Btech', 'Btech'), ('Bcom', 'Bcom'), ('Bsc', 'Bsc')], default=None, max_length=5)),
                ('contact', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
