# Generated by Django 3.0.6 on 2020-08-12 11:49

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Exam_module', '0001_initial'),
        ('auth', '0015_auto_20200812_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('mess', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('dept', models.CharField(choices=[('CS', 'Computer Science'), ('CE', 'Civil Engineering'), ('EC', 'Electronics and Communication'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering')], max_length=10)),
                ('sem', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=10)),
                ('profile_image', models.ImageField(upload_to='profile')),
                ('subjects', models.ManyToManyField(to='Exam_module.Subject')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=0)),
                ('viewed', models.BooleanField(default=False, editable=False)),
                ('out', models.BooleanField(default=False, editable=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam_module.Exam')),
                ('question_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam_module.QuestionPaper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gain', models.IntegerField(default=0)),
                ('answer', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam_module.Question')),
                ('question_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam_module.QuestionPaper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Result Out')),
                ('status', models.BooleanField(default=False, editable=False)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Student')),
            ],
            options={
                'ordering': ('-id', 'status'),
            },
        ),
    ]
